# Aktualisierte Konfigurationsdatei für Continual-Learning-Benchmark

# Test-Typ: 'replay' oder 'no_replay'
test_type: replay

# Modell-Definition , NOT USED
model_module: my_models                   # Python-Modul mit Modell-Factory
model_factory: get_model                  # Factory-Funktion


# Parameter für die Tests
params:
  countries:
    - Finland
    - Ireland
    - Serbia
    - Austria
    - Portugal
  permutation: [0, 1, 2, 3, 4]                # Reihenfolge der Länder-Indices

  # Anzahl der zufällig gezogenen Samples pro Land
  train_samples: 2200 #22482
  test_samples: 200 #8176
  seed: 42                              # Seed für Reproduzierbarkeit

  # DataLoader-Parameter
  batch_size: 16
  num_workers: 4
  epoch: 15
  lr: 1e-4


  # Bildgröße und Filteroptionen
  img_size: [12, 128, 128]
  include_snowy: false
  include_cloudy: false


  save_dir: ./saved_models                # Verzeichnis zum Speichern der Modelle
  log_every_step: true

