# Aktualisierte Konfigurationsdatei für Continual-Learning-Benchmark

# Test-Typ: 'replay' oder 'no_replay'
test_type: replay

# Modell-Definition
model_module: my_models                   # Python-Modul mit Modell-Factory
model_factory: get_model                  # Factory-Funktion
model_params:
  learning_rate: 0.001
  hidden_units: [128, 64]

# Parameter für die Tests
params:
  countries:
    - Finland
    - Ireland
    - Serbia
    - Austria
    - Portugal
  permutation: [0, 1, 2, 3, 4]                # Reihenfolge der Länder-Indices

  # Anzahl der zufällig gezogenen Samples pro Land
  train_samples: 1000 #22482
  test_samples: 100 #8176
  seed: 42                              # Seed für Reproduzierbarkeit

  # DataLoader-Parameter
  batch_size: 16
  num_workers: 8

  # Bildgröße und Filteroptionen
  img_size: [12, 128, 128]
  include_snowy: false
  include_cloudy: false

  # Training-spezifische Fit-Argumente
  fit_kwargs:
    epochs: 10
    batch_size: 16

  save_dir: ./saved_models                # Verzeichnis zum Speichern der Modelle
  log_every_step: true

