
test_type: replay

# Modell-Definition
model_module: my_models                        # Python-Modul, das die Modell-Factory enthält
model_factory: get_model                       # Funktion innerhalb des Moduls, erzeugt eine Modellinstanz
model_params:
  learning_rate: 0.001
  hidden_units: [128, 64]

# Parameter für die Tests
params:
  countries:
    - DE
    - FR
    - IT
  get_dataset: my_data_loader:get_dataset      # Pfad zum Datenloader (Modul:Fn)
  metrics_fn: my_metrics:compute_metrics       # Pfad zur Metrik-Funktion (Modul:Fn)
  fit_kwargs:
    epochs: 10
    batch_size: 32
  save_dir: ./saved_models                     # Verzeichnis zum Speichern der Modellgewichte
  log_every_step: true

